name: Build User_Activity

on:
# Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab    
  workflow_dispatch:
    inputs:
      sample_driver:
        description: 'directory'
        required: true
        default: '.'

jobs:
  build_sample_driver:
    runs-on: ubuntu-latest
    name: Build User_Activity
    steps:
      - name: Checkout local repo
        id: checkout_local_repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build c4z from manifest
        id: build
        uses: control4/drivers-driverpackager@v1
        with:
          projectDir: '${{ github.event.inputs.sample_driver }}'
          c4zproj: '${{ github.event.inputs.sample_driver }}.c4zproj'
          outputDir: '.'

      - name: Commit and push updated sample driver.c4z
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update dev c4z" -a
          git push
